name: Trigger Render Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'render.yaml'
      - '.github/workflows/deploy-backend-render.yml'

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "RENDER_DEPLOY_HOOK secret not set; skipping" && exit 0
          fi
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"



